export const getBossImage = (bossName: string) => {
  if (!bossName) return require('../assets/boss_red_dragon_manhwa.png');
  const name = bossName.toLowerCase();
  if (name.includes('dragão') || name.includes('dragao') || name.includes('dragon')) return require('../assets/boss_red_dragon_manhwa.png');
  if (name.includes('tarrasque')) return require('../assets/boss_tarrasque_manhwa.png');
  if (name.includes('rakshasa')) return require('../assets/boss_rakshasa_manhwa.png');
  if (name.includes('beholder') || name.includes('observador')) return require('../assets/boss_beholder_manhwa.png');
  if (name.includes('lich')) return require('../assets/boss_lich_manhwa.png');
  if (name.includes('golem')) return require('../assets/boss_golem_manhwa.png');
  if (name.includes('demon') || name.includes('demônio') || name.includes('demonio')) return require('../assets/boss_demon_manhwa.png');
  if (name.includes('beast') || name.includes('besta')) return require('../assets/boss_beast_manhwa.png');
  if (name.includes('demogorgon')) return require('../assets/boss_demogorgon_manhwa.png');
  if (name.includes('death knight') || name.includes('cavaleiro da morte')) return require('../assets/boss_deathknight_manhwa.png');
  if (name.includes('dracolich')) return require('../assets/boss_dracolich_manhwa.png');
  if (name.includes('medusa')) return require('../assets/boss_medusa_manhwa.png');
  if (name.includes('mimic') || name.includes('mímico') || name.includes('mimico')) return require('../assets/boss_mimic_manhwa.png');
  if (name.includes('hydra') || name.includes('hidra')) return require('../assets/boss_hydra_manhwa.png');
  if (name.includes('aboleth')) return require('../assets/boss_aboleth_manhwa.png');
  if (name.includes('wyvern') || name.includes('shadow wyvern') || name.includes('wyvern das sombras')) return require('../assets/boss_shadowwyvern_manhwa.png');
  if (name.includes('vampire') || name.includes('vampiro')) return require('../assets/boss_vampire_manhwa.png');
  if (name.includes('djinn') || name.includes('gênio') || name.includes('genio') || name.includes('maldito')) return require('../assets/boss_djinn_manhwa.png');
  if (name.includes('mind flayer') || name.includes('devorador de mentes') || name.includes('mindflayer')) return require('../assets/boss_mindflayer_manhwa.png');
  if (name.includes('yuan-ti') || name.includes('yuanti')) return require('../assets/boss_yuanti_manhwa.png');
  if (name.includes('gnoll')) return require('../assets/boss_gnoll_manhwa.png');
  if (name.includes('tiefling')) return require('../assets/boss_tiefling_manhwa.png');
  if (name.includes('naga')) return require('../assets/boss_naga_manhwa.png');
  if (name.includes('esfinge') || name.includes('sphinx')) return require('../assets/boss_esfinge_manhwa.png');
  if (name.includes('balor')) return require('../assets/boss_balor_manhwa.png');
  if (name.includes('pit fiend') || name.includes('pitfiend')) return require('../assets/boss_pitfiend_manhwa.png');
  if (name.includes('elder brain') || name.includes('elderbrain')) return require('../assets/boss_elderbrain_manhwa.png');
  if (name.includes('quimera') || name.includes('chimera')) return require('../assets/boss_chimera_manhwa.png');
  if (name.includes('urso-coruja') || name.includes('urso coruja') || name.includes('owlbear')) return require('../assets/boss_owlbear_manhwa.png');
  if (name.includes('troll')) return require('../assets/boss_troll_manhwa.png');
  if (name.includes('gorgon')) return require('../assets/boss_gorgon_manhwa.png');
  if (name.includes('drow arcano') || name.includes('drow mage') || name.includes('mago drow')) return require('../assets/boss_drowarcano_manhwa.png');
  if (name.includes('wraith') || name.includes('aparição') || name.includes('aparicao')) return require('../assets/boss_wraith_manhwa.png');
  if (name.includes('roc')) return require('../assets/boss_roc_manhwa.png');
  if (name.includes('marilith')) return require('../assets/boss_marilith_manhwa.png');
  if (name.includes('night hag') || name.includes('bruxa da noite') || name.includes('bruxa')) return require('../assets/boss_nighthag_manhwa.png');
  if (name.includes('ice devil') || name.includes('diabo do gelo') || name.includes('diabo de gelo')) return require('../assets/boss_icedevil_manhwa.png');
  if (name.includes('flameskull') || name.includes('caveira flamejante') || name.includes('caveira')) return require('../assets/boss_flameskull_manhwa.png');
  if (name.includes('chuul')) return require('../assets/boss_chuul_manhwa.png');
  return require('../assets/boss_red_dragon_manhwa.png');
};
